services:
  database:
    container_name: database
    image: postgres:13.10
    restart: always
    volumes:
      -  ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432